# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=kopkop/jupyter-cuda-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"

# Install Tensorflow
RUN pip install --quiet --no-cache-dir \
    'jupyter-server-proxy==1.6.0' \
    'tensorflow==2.4.1' \
    'tensorflow-gpu==2.4.1' \
    'jupyter-tensorboard-proxy==0.1.1' && \
    jupyter serverextension enable --sys-prefix jupyter_server_proxy && \
    jupyter labextension install @jupyterlab/server-proxy && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
